algoritmo "Conversão de Celsius em Fahrenheit"
// Função : Ler uma temperatura em graus Celsius e apresentá-la convertida em graus Fahrenheit.
// Autor :Enzo Krebs Silva
// Data : 30/03/2023
// Seção de Declarações 
var
cel: real
fah: real

inicio
escreval("Qual a temperatura em Graus Celcius a ser convertida?")
leia(cel)

//processamento
fah <- (cel*1.8)+32

//saida
escreval("A temperatura convertida em Fahrenheit fica em ", fah)

// Seção de Comandos 
fimalgoritmo
