algoritmo "Exercício 1 - Faixa etária"
// Função : Identificar se idade é maior ou igual a 10 anos
// Autor : Enzo Krebs Silva
// Data : 18/05/2023
// Seção de Declarações 
var

idade: inteiro

// Seção de Comandos
inicio

escreval ("Qual é sua idade? ")
leia (idade)

 //processamento

se (idade >=10)entao

   escreval ("Boa jogatina!")

senao

     escreval ("Esse jogo não é recomendado para crianças menores de 10 anos de idade!")

fimse

fimalgoritmo
