algoritmo "Exercício 7"
// Função : Verificar um número, e decidir se ele está entre 100 e 200
// Autor : Enzo Krebs
// Data : 25/05/2023
// Seção de Declarações 
var
numero: real

inicio
// Seção de Comandos

escreval("Qual o número?")
leia(numero)

se (numero<=200) e (numero>=100) entao
   escreval ("Seu número está entre 100 e 200")
senao
   escreval ("Seu número não está entre 100 e 200")
fimse

fimalgoritmo
